### ISSUE TITLE
Intermittent TypeError with tags subcommand

### ISSUE THREAD

**Issue by a1exsh** [zalando-stups/pierone#128]
```
$ pierone tags myteam myartifact
Traceback (most recent call last):
  File "/home/oshulgin/.local/bin/pierone", line 11, in <module>
    sys.exit(main())
  File "/home/oshulgin/.local/lib/python3.5/site-packages/pierone/cli.py", line 456, in main
    cli()
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/pierone/cli.py", line 242, in tags
    tags = get_image_tags(image, token)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/pierone/api.py", line 130, in get_image_tags
    for entry in response.json()]
  File "/home/oshulgin/.local/lib/python3.5/site-packages/pierone/api.py", line 130, in <listcomp>
    for entry in response.json()]
  File "/home/oshulgin/.local/lib/python3.5/site-packages/pierone/api.py", line 152, in parse_pierone_artifact_dict
    'tag': original_payload_from_api['name'],
TypeError: string indices must be integers
```
The team and artifact names are correct.

Retrying the command the next second works:
```
$ pierone tags myteam myartifact
Team│Artifact│Tag  │Created│By                        │Fixable CVE Severity│Unfixable CVE Severity
myteam myartifact   cd150 41d ago ... MEDIUM               MEDIUM                 
myteam myartifact   cd151 41d ago ... MEDIUM               MEDIUM    
...
```

**Comment by hjacobs** [comment]
@a1exsh wrong repo, see https://github.com/zalando-stups/pierone-cli

**Comment by a1exsh** [comment]
Ah, sorry :-)  Looks like it's already fixed there.
